// <auto-generated />
using System;
using Building.PropertyAPI.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Building.PropertyAPI.Migrations
{
    [DbContext(typeof(PropertyContext))]
    partial class PropertyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Building.PropertyAPI.Core.Entities.Property", b =>
                {
                    b.Property<Guid>("IdProperty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeInternal")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdProperty");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("Building.PropertyAPI.Core.Entities.PropertyImage", b =>
                {
                    b.Property<Guid>("IdPropertyImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdProperty")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PropertyIdProperty")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPropertyImage");

                    b.HasIndex("PropertyIdProperty");

                    b.ToTable("PropertyImage");
                });

            modelBuilder.Entity("Building.PropertyAPI.Core.Entities.PropertyImage", b =>
                {
                    b.HasOne("Building.PropertyAPI.Core.Entities.Property", "Property")
                        .WithMany("PropertyImages")
                        .HasForeignKey("PropertyIdProperty");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Building.PropertyAPI.Core.Entities.Property", b =>
                {
                    b.Navigation("PropertyImages");
                });
#pragma warning restore 612, 618
        }
    }
}
